apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: gen-barcode
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    metadata:
      name: gen-barcode
    spec:
      template:
        spec:
          containers:
          - image: nontster/python-barcode
            name: gen-barcode
            volumeMounts:
            - name: shared
              mountPath: /share
            resources:
              requests:
                memory: "64Mi"
                cpu: "250m"
              limits:
                memory: "128Mi"
                cpu: "500m"
          restartPolicy: OnFailure
          volumes:
          - name: shared
            persistentVolumeClaim:
              claimName: pybar-claim
